export const EventTypes = {
  APPOINTMENT_CONFIRMED: 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
  APPOINTMENT_RESCHEDULED: 'APPOINTMENT_RESCHEDULED',
};

export const CancellationReasons = {
  PATIENT_REQUEST: 'PATIENT_REQUEST',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
};
